### ISSUE TITLE
@this highlighting

### ISSUE THREAD

**Issue by gugiserman** [defunkt/coffee-mode#315]
Why isn't "@" highlighted as keyword in variables?

**Comment by syohex** [comment]
Could you show us screenshot or sample code ?

**Comment by gugiserman** [comment]
ubuntu 14.04, emacs 24.3, coffee-mode and monokai

![screenshot from 2015-08-04 13 57 03](https://cloud.githubusercontent.com/assets/4623123/9066938/c5169f3a-3ab0-11e5-85d9-92bacf41d480.png)

same code in WebStorm from intellij, using monokai as well:
![screenshot from 2015-08-04 13 59 00](https://cloud.githubusercontent.com/assets/4623123/9066974/f944ce26-3ab0-11e5-9b52-425705292ebc.png)

**Comment by syohex** [comment]
I see.

> Why isn't "@" highlighted as keyword in variables?

Sorry I don't understand. Original code implements such highlighting. However coffee-mode highlights `@` same as Vim, SublimeText, Atom.io.
 
### Vim

![vim](https://camo.githubusercontent.com/46b7a3e121fd0f9032af3f0e7ee34f7ad5f5e22a/687474703a2f2f692e696d6775722e636f6d2f6a314268705a512e706e67)

### SublimeText

![sublimetext](https://camo.githubusercontent.com/56da0e7db09cda09628c5c6c58965c8c3169e79a/687474703a2f2f692e696d6775722e636f6d2f324a3439512e706e67)

### Atom.io

![atom.io](https://atom.io/assets/screenshot-main-f609d95c29e5190787970f8c83762fcb.png)

**Comment by syohex** [comment]
I suppose you can customize `@` highlighting with following configuration.

```lisp
(defface my/coffee-at-mark
  '((t (:foreground "green")))
  "my at mark")

(font-lock-add-keywords
 'coffee-mode
 '(("\\(@\\)\\([_[:word:]]+\\|\\<this\\)\\>"
    (1 'my/coffee-at-mark)
    (2 font-lock-variable-name-face))))
```

Screenshot is here.

![my-own-atmark](https://cloud.githubusercontent.com/assets/554281/9084752/92379338-3bb1-11e5-9297-1255cb371533.png)

**Comment by gugiserman** [comment]
@syohex thank you very much!!!!!

**Comment by rosewd1954** [comment]
Thanks for accepting me. let me introduce my self to you,Am Mrs Delane Franco, A christian 58 years old,I have a donation to donate,Am a widow from manila phillipine, Recently my Doctor told me that I would not last for the next five months due to cancer problem. i decided to donate this fund to an organization or good person that will utilize this money the way I am going to instruct herein. Meanwhile I am not afraid of death hence I know where I am going. Whoever that Wants to serve the Lord must serve him in truth and faith, "serving him with all you have, knowing that naked we come and naked we must go" Contact me on the this email address (francodelane AT outlook.fr) and any delay in your reply will give me room in sourcing another good person, organization for this same purpose. Please assure me that you will act accordingly as I Stated herein. Remain bless in the lord. Your Sister in christ . Delane Franco
